### ISSUE TITLE
Problème de climatisation lors d’une recharge rapide

### ISSUE THREAD

**Issue by renaultcommunity** [renaultcommunity/megane-e-tech-electric#5]
### Contexte :

Plusieurs propriétaires remontent que leur véhicule accepte mal la recharge rapide, ou bien que celle-ci démarre, mais s’arrête en cours de route avec des messages d’erreur troublants comme **« charge batterie DC impossible »** ou **« anomalie batterie de traction »**. Certains reportent aussi des bruits métalliques peu rassurants lors de la charge ou un arrêt brutal de la climatisation. 

### Modèles concernés :  
   - Sans PAC (Pompe A Chaleur)

Pour les modèles sans PAC, la panne intervient lors d’une recharge rapide, lorsque la température extérieure est élevée et que celle de la batterie est comprise entre `40°` et `45°`  et souvent après un long trajet.

### Corrections : 
**Renault** a identifié une **_« faible probabilité de mise hors service du système de climatisation »_** lors d'une charge rapide. Il confirme qu’une solution a été **« appliquée à distance dans le courant du mois de septembre »**, grâce à une mise à jour logicielle en **OTA**, sans avoir besoin de se déplacer en atelier.

### Note d’information de Renault envoyée aux propriétaires de Mégane E-Tech électrique (cf image)

![note-renault-megane-e-tech-information-charge-rapide](https://user-images.githubusercontent.com/115348139/194770108-454594fa-bf9e-431a-88ce-e531937be92b.jpg)

**Comment by Noobzik** [comment]
Vu que c'est fixed, je suggère de fermer le problème

**Comment by renaultcommunity** [comment]
@Noobzik en effet. Closed du coup.
