### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Noobzik** [renaultcommunity/megane-e-tech-electric#8]
Je propose de mettre dans le README (et dans un dossier d'archivage en cas de non disponibilité) tout fichier servant de documentation à la Mégane

En voilà une. [Procedure d'installation d'une mise à jour OTA](https://cdn.group.renault.com/ren/fr/myr/pdf/FOTA_GUIDE_FINAL.pdf)

**Comment by renaultcommunity** [comment]
Très bonne idée, je l'ajoute de suite.

**Comment by renaultcommunity** [comment]
J'ai ajouté la DOC y compris la notice du véhicule et du OpenR Link.
J'ai également créé un modèle pour les issues pour fiabiliser les reports disponible ici [Bug Report template](https://github.com/renaultcommunity/megane-e-tech-electric/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml)  ou dès la creation d'une issue.

Merci.

**Comment by Noobzik** [comment]
Documentation additionnel : https://www.tech-accessoires.renault.com/renault-techaxs/search?access=searchText&q=%22RENAULT+MEGANE+E-TECH+ELECTRIC+%28BCB%29%22

**Comment by renaultcommunity** [comment]
Merci pour le link, je vais regarder ceux qu'il faut ajouter au repository et les ajouter dans le README.
